### ISSUE TITLE
Unable to establish mode 1

### ISSUE THREAD

**Issue by nirshem** [Xinyuan-LilyGO/T-Halow#16]
I flashed with the bin named "..usb" (mode1) and connected via USB-C - there is no connectivity to the PC. The pc ring up and down like the device is connected and disconnected again and again .

than i tried something else - i pushed the boot button while powering up, than i succeed to establish serial over the USB-C directly to the ESP32 - than succeed to load the bin file of STA.

Now i want the device to work as mode 1 but reboot caused the PC ringing again like the USB-C connected/disconnected , i need it for the AT commands, what your advice in this case ?

thanks

**Comment by ShallowGreen123** [comment]
![image](https://github.com/user-attachments/assets/42f9452e-0a28-4627-86af-668e65bfe1e9)

1、These two firmwares can only be downloaded to esp32 (green box)

2、These two firmwares are for the TX-AH module and cannot be downloaded to the esp32 (red box)

It is usually downloaded in the package. The default firmware for version 2 is `huge-xxxxx-usb.bin`, and the additional version is `huge-xxxxxx-WNB.bin`;

You can use `AT+VERSION=?` to check the version of the TX-AH module;

`huge-xxxxx-usb.bin`:+VERSION:v1.6.3.5-25403
`huge-xxxxxx-WNB.bin`:+VERSION:v1.6.4.3-29063

----------------
If the problem is not solved, a troubleshooting screen can be provided；

**Comment by nirshem** [comment]
Hi,

The mentioned information is known and its exactly what I did to be clarify here are the steps i followed in order to establish MODE 1 (esp32 only):

1) I burned the portable flash (**winbond chip**) with the huge-xxxxx-usb.bin
2) Than i found that the USB-C connected disconnected again and again to the PC
3) I pressed the BOOT button and succeed to establish the serial connectivity (over USB-c) to the ESP32 
4) I succeed to burn **the ESP 32** with firmare_T-halow_AP.bin (green box
5) now again after reset the **USB-C ringing again and again** and no debug info in serial

I hope this is more clearly

Thanks

**Comment by ShallowGreen123** [comment]
Can you provide a fault video？
